# Generated by Django 2.2.6 on 2019-12-19 16:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=None, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
                ('from_user', models.ForeignKey(on_delete=None, related_name='from_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
